<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>HitoriaClinica</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="ConjuntosDatos.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ConjuntosDatos.xsd</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>

    <Folder Include="Modelos\" />
    <Folder Include="Pantallas\PantallaInit\Logic\" />

    <PackageReference Include="DinkToPdf" Version="1.0.8" />

    <PackageReference Include="Google.Apis" Version="1.69.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />

    <None Include="Recursos\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <IncludeInPublish>true</IncludeInPublish>
    </None>

    <None Include="Reportes\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <IncludeInPublish>true</IncludeInPublish>
    </None>

    <None Include="dlls\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <IncludeInPublish>true</IncludeInPublish>
      <Link>%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

</Project>